### ISSUE TITLE
Directory parsing is not working well

### ISSUE THREAD

**Issue by karimelazzouni** [opierre/NRCToStrava#1]
I spent a few hours today trying to you use your tool (It is great btw!).

I faced a couple of issues with regards to packages and I had to install a couple of packages manually before retrying to run the script again (pytz being the biggest pain in the neck), so you might want to consider using a [requirements file](https://www.idkrtm.com/what-is-the-python-requirements-txt/) in the next version.

Another issue I faced was the directory parsing and file names; in your scripts you're prefixing the directories with `\\` which doesn't seem to work. On multiple occasions, I had the `tcx` files converted and ready for upload, only for the uploader not to find any of them in `TCX_exports`. After inspections, I found out that the script had converted them pretty well, but wasn't able to export or upload them to Strava because the directory was empty. I had to tweak the code (and hard-code the directory in there) in order to get it to work.

Additionally, after I finally got them exported as `tcx` files there, the uploader was not able to find any of them in the directory and failed. After removing the prefix of `\\` and hard-coding the right directory, it worked flawlessly.

Finally, thank you so much for creating such a great tool for migrating from NRC to Strava :)!

**Comment by opierre** [comment]
Thank you Karim for your feedback, I am glad to know that at least someone else used it!

Indeed you are right, I just added a _requirements.txt_ to my repository. Sorry for the time loss with Python packages.

Regarding directory parsing I was not able to reproduce your issue. However I have modified both Python scripts to handle directories safer. It should do the trick.
