### ISSUE TITLE
ValueError: astimezone() cannot be applied to a naive datetime

### ISSUE THREAD

**Issue by S1N4X** [opierre/NRCToStrava#3]
Hello,
I'm getting this error when running the script:

`Fetching https://api.nike.com/sport/v3/me/activity/92c114e0-fd9f-40ed-aff5-6b5f4422cfaf?metrics=ALL...
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
`                                 Dload  Upload   Total   Spent    Left  Speed
` '100  268k    0  268k    0     0   436k      0 --:--:-- --:--:-- --:--:--  436k`
` 
` Converting activity-92c114e0-fd9f-40ed-aff5-6b5f4422cfaf.json...
` Traceback (most recent call last):
`  File "./scripts/nrcToTcx.py", line 90, in <module>
`    convert(sys.argv[1])
`  File "./scripts/nrcToTcx.py", line 80, in convert
`    tcx = Generator(activityData)
`  File "./scripts/nrcToTcx.py", line 29, in __init__
`    self.activity = Activity(self.activities, self.data['start_epoch_ms']).activity
`  File "/nfs/scripts/lib/NRCToStrava/scripts/tcx_format/Activity.py", line 15, in __init__
`    self.id.text = epochToReadable(ident)
`  File "/nfs/scripts/lib/NRCToStrava/scripts/utils/functions.py", line 12, in epochToReadable
`    finalTime = finalTimeWithLocalUtc.astimezone(utc)
` ValueError: astimezone() cannot be applied to a naive datetime

Thanks!

**Comment by opierre** [comment]
Hello @sinaxin, 

It seems like your error occured after you retrieved your activity from Nike server. Would you mind sending me the JSON concerned (_activity-92c114e0-fd9f-40ed-aff5-6b5f4422cfaf.json_)?

I will try to look at this error.
